Hackzilla\Bundle\TicketBundle\Model\Ticket:
    properties:
        subject:
            - NotBlank: ~
            - Count: { min: 1 }
            - Valid: ~

Hackzilla\Bundle\TicketBundle\Model\TicketMessage:
    properties:
        message:
            - NotBlank: ~
