hackzilla_ticket:
    path: /
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketController::indexAction'

hackzilla_ticket_show:
    path: /{ticketId}/show
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketController::showAction'

hackzilla_ticket_new:
    path: /new
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketController::newAction'

hackzilla_ticket_create:
    path: /create
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketController::createAction'
    methods: post

hackzilla_ticket_delete:
    path: /{ticketId}/delete
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketController::deleteAction'
    methods: post|delete

hackzilla_ticket_reply:
    path: /{ticketId}/reply
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketController::replyAction'

hackzilla_ticket_attachment:
    path: /attachment/{ticketMessageId}/download
    controller: 'Hackzilla\Bundle\TicketBundle\Controller\TicketAttachmentController::downloadAction'
